FROM tomatao/breko-hub-install
MAINTAINER Thomas Hudspith-Tatham <tom@tomatao.co.uk>

ENV NODE_ENV development
ENV DEBUG *,-babel,-koa*,-css-modules*,-engine*,-socket.io*,-mocha*,-follow-redirects,-superagent

RUN yarn install

COPY src src

CMD [ "node", "./src/server-entry.js" ]
