FROM tomatao/breko-hub-install
MAINTAINER Thomas Hudspith-Tatham <tom@tomatao.co.uk>

ENV NODE_ENV test
ENV DEBUG *,-babel,-koa*,-css-modules*,-engine*,-socket.io*,-mocha*,-follow-redirects,-superagent

RUN yarn install

COPY \
  .eslintignore \
  .eslintrc \
  .istanbul.yml \
  .sass-lint.yml \
  $APP_DIR/
COPY scripts scripts
COPY src src
COPY test test

CMD [ "npm", "test" ]
